name: Publish to Maven Central

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update version in build.gradle
        run: |
          sed -i "s/version = '.*'/version = '${{ steps.get_version.outputs.VERSION }}'/" build.gradle

      - name: Run tests
        run: ./gradlew test

      - name: Build artifacts
        run: ./gradlew build

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          echo "$SIGNING_KEY" | base64 -d > signing-key.gpg
          ./gradlew publish \
            -Psigning.keyId=$SIGNING_KEY_ID \
            -Psigning.password=$SIGNING_PASSWORD \
            -Psigning.secretKeyRingFile=signing-key.gpg
          rm signing-key.gpg

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## LogBull Java ${{ steps.get_version.outputs.VERSION }}

            ### Maven
            ```xml
            <dependency>
                <groupId>com.logbull</groupId>
                <artifactId>logbull</artifactId>
                <version>${{ steps.get_version.outputs.VERSION }}</version>
            </dependency>

            <dependency>
                <groupId>com.logbull</groupId>
                <artifactId>logbull-spring-boot-starter</artifactId>
                <version>${{ steps.get_version.outputs.VERSION }}</version>
            </dependency>
            ```

            ### Gradle
            ```groovy
            implementation 'com.logbull:logbull:${{ steps.get_version.outputs.VERSION }}'
            implementation 'com.logbull:logbull-spring-boot-starter:${{ steps.get_version.outputs.VERSION }}'
            ```
